/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pikacu
 */
public class Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spesialis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jeniskelamin = new javax.swing.JTextField();
        golongandarah = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        kewarganegaraan = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pemilihan Dokter");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 10, 210, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pilih Dokter");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 80, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Dr. Farras Yassar", "Dr. Dian Nofika", "Dr. Harun Fajar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 80, 190, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 80, 80, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nama");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 50, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Usia");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 110, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 140, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Golongan Darah");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 170, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Status");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 200, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Dokter Spesialis");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 290, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Kewarganegaraan");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 230, 130, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Waktu Praktek");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 260, 110, 30);
        jPanel2.add(spesialis);
        spesialis.setBounds(230, 280, 170, 30);
        jPanel2.add(nama);
        nama.setBounds(230, 40, 170, 30);
        jPanel2.add(alamat);
        alamat.setBounds(230, 70, 170, 30);
        jPanel2.add(usia);
        usia.setBounds(230, 100, 170, 30);
        jPanel2.add(jeniskelamin);
        jeniskelamin.setBounds(230, 130, 170, 30);
        jPanel2.add(golongandarah);
        golongandarah.setBounds(230, 160, 170, 30);
        jPanel2.add(status);
        status.setBounds(230, 190, 170, 30);
        jPanel2.add(kewarganegaraan);
        kewarganegaraan.setBounds(230, 220, 170, 30);
        jPanel2.add(waktu);
        waktu.setBounds(230, 250, 170, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 140, 440, 340);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pilih Dokter");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 230, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 490);

        setBounds(0, 0, 534, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Dr. Farras Yassar")){
            nama.setText("Dr. Farras Yassar");
            alamat.setText("Jl. Surabaya 16, Malang");
            usia.setText("20 tahun");
            jeniskelamin.setText("Laki - Laki");
            golongandarah.setText("A");
            status.setText("Belum Menikah");
            kewarganegaraan.setText("Indonesia");
            waktu.setText("Pagi 07.00 - 15.00");
            spesialis.setText("Dokter Umum");
        }
        else if(jComboBox1.getSelectedItem().equals("Dr. Dian Nofika")){
            nama.setText("Dr. Dian Nofika");
            alamat.setText("Jl. Danau Poso, Malang");
            usia.setText("20 tahun");
            jeniskelamin.setText("Perempuan");
            golongandarah.setText("O");
            status.setText("Belum Menikah");
            kewarganegaraan.setText("Indonesia");
            waktu.setText("Malam 16.00 - 22.00");
            spesialis.setText("Dokter Mata");
        }
        else if  (jComboBox1.getSelectedItem().equals("Dr. Harun Fajar")){
            nama.setText("Dr. Harun Fajar");
            alamat.setText("Jl. Danau Towuti, Malang");
            usia.setText("25 tahun");
            jeniskelamin.setText("Laki-Laki");
            golongandarah.setText("AB");
            status.setText("Menikah");
            kewarganegaraan.setText("Indonesia");
            waktu.setText("Siang 11.00 - 16.00");
            spesialis.setText("Dokter Hati");
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField golongandarah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jeniskelamin;
    private javax.swing.JTextField kewarganegaraan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField spesialis;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
