
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pikacu
 */
public class Praktikum_2_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum_2_GUI
     */
    public Praktikum_2_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bb = new javax.swing.JRadioButton();
        meat = new javax.swing.JRadioButton();
        ss = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        gambarss = new javax.swing.JLabel();
        gambarmeat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        besar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sedang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTextArea();
        gambarbb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("XPRT PIZZA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 10, 220, 60);

        bb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bb.setText("BIG BOX");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        jPanel1.add(bb);
        bb.setBounds(20, 110, 130, 25);

        meat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meat.setText("MEAT LOVERS");
        meat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatActionPerformed(evt);
            }
        });
        jPanel1.add(meat);
        meat.setBounds(20, 230, 140, 25);

        ss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ss.setText("SUPER SUPREME");
        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });
        jPanel1.add(ss);
        ss.setBounds(20, 350, 150, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("ISI");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 340, 70, 30);

        gambarss.setIcon(new javax.swing.ImageIcon("G:\\XIRPL3_SEMESTER 2\\PBO\\Modul_9\\ss.jpg")); // NOI18N
        jPanel1.add(gambarss);
        gambarss.setBounds(270, 80, 270, 160);

        gambarmeat.setIcon(new javax.swing.ImageIcon("G:\\XIRPL3_SEMESTER 2\\PBO\\Modul_9\\mll.jpg")); // NOI18N
        jPanel1.add(gambarmeat);
        gambarmeat.setBounds(270, 80, 270, 160);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("PORSI BESAR");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 300, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("HARGA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 260, 70, 30);
        jPanel1.add(besar);
        besar.setBounds(450, 300, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("PORSI SEDANG");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 260, 100, 30);
        jPanel1.add(sedang);
        sedang.setBounds(450, 260, 110, 30);

        isi.setColumns(20);
        isi.setRows(5);
        jScrollPane1.setViewportView(isi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(390, 340, 166, 96);

        gambarbb.setIcon(new javax.swing.ImageIcon("G:\\XIRPL3_SEMESTER 2\\PBO\\Modul_9\\bb.PNG")); // NOI18N
        jPanel1.add(gambarbb);
        gambarbb.setBounds(270, 80, 270, 160);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 130, 34, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 450);

        setBounds(0, 0, 597, 484);
    }// </editor-fold>//GEN-END:initComponents

    
    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        if(bb.isSelected()){
            sedang.setText("kosong");
            besar.setText("Rp. 280.000");
            isi.setText("Garlic Bread(8) \nFish Finger(6) \n Chicken Sticks(8) \n Nasi Chicken Delight \n Meat Lovers - Pan Pizza Besar \n Cheese - Beef Fusilli");
            gambarbb.setVisible(true);
            gambarmeat.setVisible(false);
            gambarss.setVisible(false);
        }
        else {
            sedang.setText("");
            besar.setText("");
            isi.setText("");
            gambarbb.setVisible(false);
            gambarmeat.setVisible(false);
            gambarss.setVisible(false);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void meatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatActionPerformed
        if(meat.isSelected()){
            sedang.setText("Rp. 90.000");
            besar.setText("Rp. 120.000");
            isi.setText("Irisan sosis sapi \n daging sapi cincang \n burger sapi \n sosis ayam");
            gambarbb.setVisible(false);
            gambarmeat.setVisible(true);
            gambarss.setVisible(false);
        }
        else {
            sedang.setText("");
            besar.setText("");
            isi.setText("");
            gambarbb.setVisible(false);
            gambarmeat.setVisible(false);
            gambarss.setVisible(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_meatActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
        if(ss.isSelected()){
            sedang.setText("Rp. 224.000");
            besar.setText("Rp. 160.000");
            isi.setText("Daging ayam dan sapi asap \n daging sapi cincang \n burger sapi \n jamur \n paprika merah \n paprika hijau");
            gambarbb.setVisible(false);
            gambarmeat.setVisible(false);
            gambarss.setVisible(true);
        }
        else {
            sedang.setText("");
            besar.setText("");
            isi.setText("");
            gambarbb.setVisible(false);
            gambarmeat.setVisible(false);
            gambarss.setVisible(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum_2_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bb;
    private javax.swing.JTextField besar;
    private javax.swing.JLabel gambarbb;
    private javax.swing.JLabel gambarmeat;
    private javax.swing.JLabel gambarss;
    private javax.swing.ButtonGroup group;
    private javax.swing.JTextArea isi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton meat;
    private javax.swing.JTextField sedang;
    private javax.swing.JRadioButton ss;
    // End of variables declaration//GEN-END:variables
}
